/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBurnable__factory } from "./IBurnable__factory";
export { TournamentManager__factory } from "./TournamentManager__factory";
