/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tournamentManagerSol from "./TournamentManager.sol";
export type { tournamentManagerSol };
export type { GameToken } from "./GameToken";
export type { GameTokenICO } from "./GameTokenICO";
export type { MockUSDT } from "./MockUSDT";
